# Generated by Django 3.1.7 on 2021-04-09 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210408_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='fecha1',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='fecha2',
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 0, 38, 54, 262319, tzinfo=utc)),
        ),
    ]
