# Generated by Django 3.1.7 on 2021-04-09 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20210409_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 0, 40, 12, 919394, tzinfo=utc)),
        ),
    ]
