# Generated by Django 3.1.7 on 2021-04-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20210410_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='rentabilidad_horas',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rentabilidad_presupuesto',
            field=models.FloatField(default=1, null=True),
        ),
    ]
